### ISSUE TITLE
Exception on diff

### ISSUE THREAD

**Issue by fiee** [barry-scott/scm-workbench#13]
Diffing files doesn’t work. Log complains about a styling error:
```
2019-10-20 18:46:53,919 ERROR excepthook called
2019-10-20 18:46:53,919 ERROR Traceback (most recent call last):
2019-10-20 18:46:53,919 ERROR   File "wb_svn_ui_actions.pyc", line 67, in treeTableActionSvnDiffBaseVsWorking
2019-10-20 18:46:53,920 ERROR   File "wb_scm_main_window.pyc", line 1057, in callTreeOrTableFunction
2019-10-20 18:46:53,920 ERROR   File "wb_svn_ui_actions.pyc", line 519, in tableActionSvnDiffBaseVsWorking
2019-10-20 18:46:53,920 ERROR   File "wb_ui_actions.pyc", line 86, in diffTwoFiles
2019-10-20 18:46:53,920 ERROR   File "wb_diff_side_by_side_view.pyc", line 53, in __init__
2019-10-20 18:46:53,920 ERROR   File "wb_diff_side_by_side_view.pyc", line 221, in __init__
2019-10-20 18:46:53,920 ERROR   File "wb_diff_side_by_side_view.pyc", line 300, in __init__
2019-10-20 18:46:53,921 ERROR   File "wb_scintilla.pyc", line 143, in styleSetFromSpec
2019-10-20 18:46:53,921 ERROR AssertionError: Unknown name 'size' in css 'size:12,face:Monaco,fore:#000000,back:#ffffff'
2019-10-20 18:46:53,924 ERROR Check log for traceback details
```
This is from my .app built on MacPorts Python 3.7.

I tried to run from source to check further, but PyQt5 doesn’t want (see #12).

**Comment by barry-scott** [comment]
This is only a problem in light mode. (I tested in dark mode only...)

pushing "Fix styles for light mode diff setup." id 666c8fc2ea932f7c38feb4a58db710c0e8a81d24

**Comment by fiee** [comment]
Yes, this works now, thank you!
