### ISSUE TITLE
UnicodeDecodeError with commit messages

### ISSUE THREAD

**Issue by fiee** [barry-scott/scm-workbench#15]
```
Traceback (most recent call last):
  File "logging/__init__.pyc", line 1084, in emit
UnicodeEncodeError: 'ascii' codec can't encode character '\u2019' in position 45: ordinal not in range(128)
Call stack:
  File "/Applications/SCM Workbench.app/Contents/Resources/__boot__.py", line 92, in <module>
  File "/Applications/SCM Workbench.app/Contents/Resources/__boot__.py", line 75, in _run
  File "/Applications/SCM Workbench.app/Contents/Resources/wb_scm_main.py", line 24, in <module>
  File "wb_main.pyc", line 41, in main
  File "wb_background_thread.pyc", line 139, in __runInForeground
  File "wb_background_thread.pyc", line 39, in __call__
  File "logging/__init__.pyc", line 1434, in info
  File "logging/__init__.pyc", line 1577, in _log
  File "logging/__init__.pyc", line 1587, in handle
  File "logging/__init__.pyc", line 1649, in callHandlers
  File "logging/__init__.pyc", line 950, in handle
  File "wb_logging.pyc", line 455, in emit
  File "logging/__init__.pyc", line 1183, in emit
  File "logging/__init__.pyc", line 1089, in emit
```

Current dmg version plus PySVN 1.9.12 on OSX 10.14

**Comment by fiee** [comment]
It happens always if I use non-ASCII character in Subversion commit messages. The commit works, though.

**Comment by barry-scott** [comment]
I can reproduce the problem. Hope to have a fix soon.
Sadly the bug hides when I turn on debug options.
You can also turn on debug options like this:
$ open -a 'scm workbench' --args --debug threading
If you start SCM workbench like that does it stop tracebacking for you as well?

**Comment by barry-scott** [comment]
I think I have found the problem. It seems to be a bug in the log rotate logic.
After SCM Workbench rotates its log file the new log file seems to be opened in 'ascii' encoding,
but I do not why that would be the case. But its only explaination I have for the traceback.

Can you test this version and see if the problem is fixed?

https://scm-workbench.barrys-emacs.org/kits/SCM-Workbench-0.9.5.dmg

**Comment by fiee** [comment]
Thank you, it’s fixed.
(Sorry for the slow response, I was moving.)
