### ISSUE TITLE
Two Trace backs in SVN code

### ISSUE THREAD

**Issue by barry-scott** [barry-scott/scm-workbench#6]
2016-08-29 15:22:23,656 ERROR function failed on background thread
2016-08-29 15:22:23,656 ERROR Traceback (most recent call last):

2016-08-29 15:22:23,656 ERROR   File "C:\Program Files\Barry Scott\SCM Workbench\PyWinAppRes\wb_background_thread.py", line 47, in run
    function()

2016-08-29 15:22:23,656 ERROR   File "C:\Program Files\Barry Scott\SCM Workbench\PyWinAppRes\wb_background_thread.py", line 25, in **call**
    self.function( *self.args )

2016-08-29 15:22:23,656 ERROR   File "C:\Program Files\Barry Scott\SCM Workbench\PyWinAppRes\wb_background_thread.py", line 160, in queueNextSwitch
    where_to_go_next = next( generator )

2016-08-29 15:22:23,656 ERROR   File "C:\Program Files\Barry Scott\SCM Workbench\PyWinAppRes\wb_svn_ui_components.py", line 249, in __commitAccepted
    commit_id = svn_project.cmdCommit( message )

2016-08-29 15:22:23,656 ERROR   File "C:\Program Files\Barry Scott\SCM Workbench\PyWinAppRes\wb_svn_project.py", line 328, in cmdCommit
    recurse=True )

2016-08-29 15:22:23,672 ERROR pysvn._pysvn_3_5.ClientError: ("Commit failed (details follow):\nFile 'C:\Users\barry\wc\svn\PyCXX\README.html' is out of date\nFile '/trunk/CXX/README.html' is out of date", [('Commit failed (details follow):', 155011), ("File 'C:\Users\barry\wc\svn\PyCXX\README.html' is out of date", 155011), ("File '/trunk/CXX/README.html' is out of date", 170004)])

2016-08-29 15:22:30,170 INFO U   C:/Users/barry/wc/svn/PyCXX/SourceForge/PyCXX-Python2.html
2016-08-29 15:22:30,185 INFO U   C:/Users/barry/wc/svn/PyCXX/SourceForge/PyCXX-Python3.html
2016-08-29 15:22:30,201 INFO U   C:/Users/barry/wc/svn/PyCXX/SourceForge/README.html
2016-08-29 15:22:30,201 INFO U   C:/Users/barry/wc/svn/PyCXX/SourceForge/style.css
2016-08-29 15:22:30,248 INFO U   C:/Users/barry/wc/svn/PyCXX/SourceForge/index.html
2016-08-29 15:22:30,295 INFO U   C:/Users/barry/wc/svn/PyCXX/tag_pycxx.py
2016-08-29 15:22:30,310 INFO U   C:/Users/barry/wc/svn/PyCXX/PyCXX-Release-Notes.txt
2016-08-29 15:22:30,326 INFO U   C:/Users/barry/wc/svn/PyCXX/README.html
2016-08-29 15:22:30,373 INFO U   C:/Users/barry/wc/svn/PyCXX/how_to_release_pycxx.txt
2016-08-29 15:22:30,373 INFO U   C:/Users/barry/wc/svn/PyCXX/README.txt
2016-08-29 15:22:30,451 INFO Updated PyCXX (trunk):. to revision 369, 10 new updates
2016-08-29 15:22:52,268 ERROR excepthook called
2016-08-29 15:22:52,268 ERROR Traceback (most recent call last):
2016-08-29 15:22:52,268 ERROR   File "C:\Program Files\Barry Scott\SCM Workbench\PyWinAppRes\wb_svn_ui_actions.py", line 130, in treeActionSvnDiffBaseVsWorking    diff_text = tree_node.project.cmdDiffFolder( tree_node.relativePath(), head=False )
2016-08-29 15:22:52,268 ERROR   File "C:\Program Files\Barry Scott\SCM Workbench\PyWinAppRes\wb_svn_project.py", line 279, in cmdDiffFolder    use_git_diff_format=True
2016-08-29 15:22:52,268 ERROR pysvn._pysvn_3_5.ClientError: ("Path 'C:/Users/barry/wc/svn/PyCXX/CXX/Python3/Objects.hxx' must be an immediate child of the directory 'C:\Users\barry\wc\svn\PyCXX'", [("Path 'C:/Users/barry/wc/svn/PyCXX/CXX/Python3/Objects.hxx' must be an immediate child of the directory 'C:\Users\barry\wc\svn\PyCXX'", 125007)])
2016-08-29 15:22:52,268 ERROR Check log for traceback details
2016-08-29 15:23:42,225 INFO "C:/Program Files/Barry Scott/Barry's Emacs 8/bemacs.exe" "C:\Users\barry\wc\git\scm-workbench\Source\Common\wb_platform_win32_specific.py"

: 15:24:30.76 C:\Users\barry\AppData\Roaming
: \BLACKSTAR\barry>

**Comment by barry-scott** [comment]
Fix in commit c8c4611ae8eba69a6b925a575572c9f300cb0125
